## Exercise 5_05

In [ ]:
#@title Importing modules
import pandas as pd
from sklearn.cluster import KMeans
import altair as alt
import numpy as np

In [ ]:
#@title data url
file_url = 'https://raw.githubusercontent.com/fenago/DSBook/main/Chapter%205/Mall_Customers.csv'

In [ ]:
#@title loading data
data = pd.read_csv(file_url, \
                 usecols=['Age', \
                          'Annual Income (k$)', \
'Spending Score (1-100)'])

In [ ]:
#@title displaying first 5 entries
data.head()

In [ ]:
#@title Assigning extracted col.s to a new variable
X = data[['Age', \
        'Annual Income (k$)']]

In [ ]:
#@title Now, calculate the minimum and maximum using the min() and max() values
age_min = data['Age'].min()
age_max = data['Age'].max()
annual_inc_min = data['Annual Income (k$)'].min()
annual_inc_max = data['Annual Income (k$)']\
                        .max()

In [ ]:
#@title Print the values of these four variables
print(age_min)
print(age_max)
print(annual_inc_min)
print(annual_inc_max)

In [ ]:
#@title Now import the random package and use the seed() method to set a seed of 
42
import random
random.seed(42)

In [ ]:
#@title Create an empty pandas DataFrame and assign it to a variable called centroids
centroids = pd.DataFrame()

In [ ]:
#@title Generate four random values using the sample() method from the randompackage with possible values between the minimum and maximum values
centroids\
['Age'] = random.sample (range\
        (age_min, age_max), 4)

In [ ]:
#@title Repeat the same process to generate 4 random values for total income
centroids\
['Annual Income (k$)'] = random.sample\
                                      (range\
(annual_inc_min,annual_inc_max), 4)

In [ ]:
#@title Create a new column called 'cluster' from the centroids DataFrame
centroids['cluster'] = centroids.index
centroids

In [ ]:
#@title Create a scatter plot with the altair package to display the data contained in the df DataFrame and save it in a variable called 'chart1'
chart1 = alt.Chart(data.head()).mark_circle()\
            .encode(x='Age', \
                    y='Annual Income (k$)', \
                    color=alt.value('orange'), \
                    tooltip=['Spending Score (1-100)', \
                             'Age', \
'Annual Income (k$)'])\
                   .interactive()

In [ ]:
#@title Now create a second scatter plot using the altair package to display the centroids and save it in a variable called 'chart2'
chart2 = alt.Chart(centroids).mark_circle(size=100)\
            .encode(x='Age', \
                    y='Annual Income (k$)', \
                    color=alt.value('black'), \
                    tooltip=['cluster', \
                             'Age',\
'Annual Income (k$)'])\
                   .interactive()

In [ ]:
#@title Display the two charts together using the altair syntax: <chart> + <chart>:
chart1 + chart2

In [ ]:
#@title Define a function that will calculate the squared_euclidean distance and return its value. 
def squared_euclidean(data_x, data_y, \
                      centroid_x, centroid_y, ):
    return (data_x - centroid_x)**2 + (data_y - centroid_y)**2

In [ ]:
#@title Using the .at method from the pandas package, extract the first row's x and ycoordinates and save them in two variables called data_x and data_y
data_x = data.at[0, 'Age']
data_y = data.at[0, 'Annual Income (k$)']

In [ ]:
#@title Using a for loop or list comprehension, calculate the squared_euclidean distance of the first observation (using its data_x and data_y coordinates) against the 4 different centroids contained in centroids
distances = [squared_euclidean\
             (data_x, data_y, centroids.at\
              [i, 'Age'], \
              centroids.at[i, \
              'Annual Income (k$)']) \
              for i in range(4)]
distances

In [ ]:
#@title Use the index method from the list containing the squared_euclidean distances to find the cluster with the shortest distance
cluster_index = distances.index(min(distances))

In [ ]:
#@title Save the cluster index in a column called 'cluster' 
data.at[0, 'cluster'] = cluster_index

In [ ]:
#@title Display the first five rows
data.head()

In [ ]:
#@title Repeat Steps 15 to 19 for the next 4 rows to calculate their distances from the  centroids and find the cluster with the smallest distance value
distances = [squared_euclidean\
             (data.at[1, 'Age'], \
              data.at[1, 'Annual Income (k$)'], \
              centroids.at[i, 'Age'],\
              centroids.at[i, \
                           'Annual Income (k$)'])\
             for i in range(4)]
data.at[1, 'cluster'] = distances.index(min(distances))
distances = [squared_euclidean\
             (data.at[2, 'Age'], \
              data.at[2, 'Annual Income (k$)'], \
              centroids.at[i, 'Age'],\
              centroids.at[i, \
                           'Annual Income (k$)'])\
             for i in range(4)]
data.at[2, 'cluster'] = distances.index(min(distances))
distances = [squared_euclidean\
             (data.at[3, 'Age'], \
              data.at[3, 'Annual Income (k$)'], \
              centroids.at[i, 'Age'],\
              centroids.at[i, \
                           'Annual Income (k$)'])\
             for i in range(4)]
data.at[3, 'cluster'] = distances.index(min(distances))
distances = [squared_euclidean\
             (data.at[4, 'Age'], \
              data.at[4, 'Annual Income (k$)'], \
              centroids.at[i, \
              'Age'], \
              centroids.at[i, \
              'Annual Income (k$)']) \
             for i in range(4)]
data.at[4, 'cluster'] = distances.index(min(distances))
data.head()

In [ ]:
#@title Finally, plot the centroids and the first 5 rows of the dataset using the altair package 
chart1 = alt.Chart(data.head()).mark_circle()\
            .encode(x='Age', \
                    y='Annual Income (k$)', \
                    color='cluster:N', \
                    tooltip=['Spending Score (1-100)', 'cluster', \
                             'Age', \
'Annual Income (k$)'])\
                   .interactive()
chart2 = alt.Chart(centroids).mark_circle(size=100)\
            .encode(x='Age', \
                    y='Annual Income (k$)', \
                    color=alt.value('black'), \
                    tooltip=['cluster', \
                             'Age',\
'Annual Income (k$)'])\
                   .interactive()
chart1 + chart2